---
- name: ANSISTRANO | HOOKS | Set .htaccess
  template:
    src: '{{ playbook_dir }}/roles/hooks/templates/.htaccess.j2'
    dest: '{{ roles_common_document_root }}/web/.htaccess'
    owner: '{{ roles_common_deploy_user }}'
    group: '{{ roles_common_apache_running_user }}'
    mode: 0775
  become: yes
